"""
FABRICATED BENCHMARK DATASET GENERATOR
======================================
The records generated by this script are entirely synthetic, fabricated mock entities
created specifically for public demonstration, architectural validation, and compliance
with Amazon ML Challenge 2026 data redistribution restrictions.

ZERO proprietary competition records are copied, derived, or redistributed by this script.
All business names, addresses, and variations are generated from procedural synthetic vocabulary banks.
"""
import gzip
import json
import math
import random
import sys
from collections import Counter
from pathlib import Path
import polars as pl

# Import normalization pipeline
import normalize

# Enforce deterministic generation
random.seed(42)

DEMO_DIR = Path(__file__).resolve().parent
TRANSLIT_PATH = DEMO_DIR / "translit.json"

tr = {"name": {}, "addr": {}}
if TRANSLIT_PATH.exists():
    with open(TRANSLIT_PATH, "r", encoding="utf-8") as f:
        tr = json.load(f)

# Large vocabulary building blocks
US_FIRST = ["Payne", "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez",
            "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson",
            "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis",
            "Robinson", "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill",
            "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter"]

US_STEMS = ["Apex", "Nova", "Summit", "Vanguard", "Zenith", "Pinnacle", "Nexus", "Quantum", "Omega", "Silverline",
            "Aero", "Bio", "Eco", "Neo", "Omni", "Solar", "Terra", "Urban", "Velo", "Vista", "Alpha", "Beta",
            "Prime", "Global", "Pacific", "Atlantic", "Beacon", "Crest", "Frontier", "Horizon", "Iron", "Key",
            "Liberty", "Matrix", "North", "Orbit", "Peak", "Quest", "Ridge", "Star", "Titan", "Union", "Vector",
            "Aura", "Blue", "Clear", "Direct", "Elevate", "First", "Gateway", "Harbor", "Insight", "Keystone"]

US_INDUSTRY = ["Enterprises", "Logistics", "Technologies", "Consulting", "Solutions", "Ventures", "Industries",
               "Partners", "Capital", "Holdings", "Manufacturing", "Healthcare", "Services", "Media", "Energy",
               "Systems", "Designs", "Innovations", "Dynamics", "Labs", "Supply", "Freight", "Analytics", "Network"]

US_LEGAL = ["Inc", "LLC", "Corp", "Corporation", "Co", "Company", "Ltd", "Group", "LLP"]

US_STREET_NAMES = ["Fremont", "Main", "Oak", "Maple", "Pine", "Washington", "Park", "Market", "Cedar", "Elm",
                   "Lake", "Highland", "Lincoln", "Jefferson", "Church", "Chestnut", "Walnut", "Spring", "Broad",
                   "Center", "Adams", "Jackson", "Franklin", "Laurel", "Willow", "Cypress", "Madison", "Sunset",
                   "Valley", "River", "Meadow", "Hillside", "Forest", "Ridge", "Beacon", "Grand", "Fairview"]
US_STREET_TYPES = ["Street", "Avenue", "Boulevard", "Road", "Drive", "Lane", "Way", "Court", "Place", "Parkway"]

US_CITIES = [("Peoria", "IL", "61602"), ("Chicago", "IL", "60601"), ("Austin", "TX", "78701"),
             ("Denver", "CO", "80202"), ("Seattle", "WA", "98101"), ("Boston", "MA", "02108"),
             ("Atlanta", "GA", "30303"), ("Miami", "FL", "33101"), ("New York", "NY", "10001"),
             ("Columbus", "OH", "43215"), ("Phoenix", "AZ", "85001"), ("Dallas", "TX", "75201"),
             ("San Jose", "CA", "95113"), ("Philadelphia", "PA", "19102"), ("Charlotte", "NC", "28202"),
             ("Indianapolis", "IN", "46204"), ("San Francisco", "CA", "94102"), ("Nashville", "TN", "37201")]

IN_FIRST = ["Hotel Enterprises", "Sharma", "Patel", "Gupta", "Verma", "Singh", "Kumar", "Rao", "Reddy", "Mehta",
            "Chopra", "Joshi", "Bansal", "Agarwal", "Bhatia", "Malhotra", "Saxena", "Kapoor", "Nair", "Iyer",
            "Chatterjee", "Mukherjee", "Ghosh", "Das", "Sen", "Bose", "Dutta", "Roy", "Choudhury", "Banerjee",
            "Deshmukh", "Kulkarni", "Patil", "Pawar", "Shinde", "Jadhav", "Gaikwad", "Chavan", "Sawant", "Bhat",
            "Hegde", "Pai", "Kamath", "Shenoy", "Prabhu", "Nayak", "Menon", "Nambiar", "Kurup", "Varma"]

IN_STEMS = ["Bharat", "Hindustan", "Swastik", "Shree", "Mahalaxmi", "Balaji", "Surya", "Ganesh", "Krishna", "Om",
            "Royal", "National", "Standard", "Premier", "Universal", "Super", "Asian", "Orient", "Sunrise", "Golden",
            "Galaxy", "Reliance", "Tata", "Adani", "Birla", "Godrej", "Mahindra", "Bajaj", "TVS", "Hero"]

IN_INDUSTRY = ["Enterprises", "Industries", "Infotech", "Textiles", "Motors", "Traders", "Logistics", "Electronics",
               "Foods", "Pharma", "Steels", "Jewellers", "Exports", "Solutions", "Services", "Chemicals", "Hardware",
               "Automobiles", "Polymers", "Packaging", "Ceramics", "Plastics", "Engineering", "Agro", "Cements"]

IN_LEGAL = ["Pvt Ltd", "Private Limited", "Ltd", "Limited", "& Co", "LLP", "Traders", "Corporation", "Agency", "Brothers"]

IN_LOCALITY_TYPES = ["Nagar", "Colony", "Vihar", "Enclave", "Extension", "Layout", "Bazar", "Market", "Gali", "Phase", "Sector"]
IN_LOCALITY_NAMES = ["Gandhi", "Nehru", "Subhash", "Shivaji", "Indira", "Rajendra", "Shastri", "Tilak", "Patel", "Ambedkar",
                     "Sarojini", "Lajpat", "Karol", "Connaught", "MG", "Anna", "Kamaraj", "Netaji", "Tagore", "Vivekananda"]

IN_CITIES = [("New Delhi", "Delhi", "110018"), ("Mumbai", "Maharashtra", "400001"),
             ("Bengaluru", "Karnataka", "560001"), ("Hyderabad", "Telangana", "500001"),
             ("Chennai", "Tamil Nadu", "600001"), ("Pune", "Maharashtra", "411001"),
             ("Kolkata", "West Bengal", "700001"), ("Ahmedabad", "Gujarat", "380001"),
             ("Jaipur", "Rajasthan", "302001"), ("Surat", "Gujarat", "395001"),
             ("Lucknow", "Uttar Pradesh", "226001"), ("Kanpur", "Uttar Pradesh", "208001")]

DEVANAGARI_BASES = [
    ("होटल एंटरप्राइजेज", "Hotel Enterprises"),
    ("शर्मा ट्रेडर्स", "Sharma Traders"),
    ("पटेल इन्फोटेक", "Patel Infotech"),
    ("गुप्ता ब्रदर्स", "Gupta Brothers"),
    ("वर्मा लॉजिस्टिक्स", "Verma Logistics"),
    ("कुमार टेक्सटाइल्स", "Kumar Textiles"),
    ("सिंह मोटर्स", "Singh Motors"),
    ("मेहता फार्मा", "Mehta Pharma"),
    ("अग्रवाल स्वीट्स", "Agarwal Sweets"),
    ("जोशी कंसल्टेंसी", "Joshi Consultancy"),
    ("भारत इलेक्ट्रॉनिक्स", "Bharat Electronics"),
    ("श्री गणेश इंडस्ट्रीज", "Shree Ganesh Industries"),
    ("बालाजी केमिकल्स", "Balaji Chemicals"),
    ("सूर्य टेक्सटाइल्स", "Surya Textiles"),
    ("महालक्ष्मी स्टील्स", "Mahalaxmi Steels"),
    ("ओम साईं ज्वैलर्स", "Om Sai Jewellers"),
    ("स्वस्तिक पॉलीमर्स", "Swastik Polymers"),
    ("कृष्णा ऑटोमोबाइल्स", "Krishna Automobiles"),
    ("रॉयल हार्डवेयर", "Royal Hardware"),
    ("सुपर पैकेजिंग", "Super Packaging")
]

FR_FIRST = ["Thermal & Fils", "Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Dubois", "Moreau",
            "Laurent", "Simon", "Michel", "Lefebvre", "Leroy", "Roux", "David", "Bertrand", "Morel", "Fournier",
            "Girard", "Bonnet", "Dupont", "Lambert", "Fontaine", "Rousseau", "Vincent", "Muller", "Lefevre", "Faure",
            "Andre", "Mercier", "Blanc", "Guerin", "Boyer", "Garnier", "Chevalier", "Francois", "Legrand", "Gauthier",
            "Garcia", "Perron", "Robin", "Clement", "Morin", "Nicolas", "Henry", "Roussel", "Mathieu", "Gautier"]

FR_INDUSTRY = ["Plomberie", "Transports", "Ingenierie", "Conseil", "Electricite", "Menuiserie", "Peinture",
               "Mecanique", "Boucherie", "Boulangerie", "Restauration", "Batiment", "Services", "Logistique",
               "Chauffage", "Couverture", "Macconnerie", "Carrelage", "Serrurerie", "Nettoyage", "Immobilier"]

FR_LEGAL = ["SASU", "SAS", "SARL", "EURL", "SCI", "SA", "et Fils", "& Cie", "Societe"]

FR_STREET_NAMES = ["Parmentier", "de la Republique", "Jean Jaures", "Victor Hugo", "de Paris", "Nationale",
                   "de la Gare", "des Fleurs", "Pasteur", "Gambetta", "Jules Ferry", "General de Gaulle",
                   "Carnot", "Voltaire", "Zola", "Verdun", "Fontaine", "Saint-Honore", "Lafayette", "Moulin"]
FR_STREET_TYPES = ["Rue", "Avenue", "Boulevard", "Allée", "Place", "Impasse", "Route", "Chemin", "Quai"]

FR_CITIES = [("Dunkerque", "Hauts-de-France", "59140"), ("Paris", "Ile-de-France", "75001"),
             ("Lyon", "Auvergne-Rhone-Alpes", "69001"), ("Marseille", "Provence-Alpes-Cote d'Azur", "13001"),
             ("Lille", "Hauts-de-France", "59000"), ("Bordeaux", "Nouvelle-Aquitaine", "33000"),
             ("Nantes", "Pays de la Loire", "44000"), ("Toulouse", "Occitanie", "31000"),
             ("Strasbourg", "Grand Est", "67000"), ("Rennes", "Bretagne", "35000"),
             ("Nice", "Provence-Alpes-Cote d'Azur", "06000"), ("Montpellier", "Occitanie", "34000")]

raw_records = []

# ==============================================================================
# 1. GROUND TRUTH BENCHMARK CLUSTERS (FOR EXACT PRESET VERIFICATION)
# ==============================================================================

# Preset 1 Cluster (US: Payne Enterprises)
raw_records.append(("S2-10001", "Payne Enterprises Inc", "3315 Fremont St, Peoria, IL 61602", "us"))
raw_records.append(("S3-10002", "Payne Enterprises LLC", "3315 Fremont Street, Peoria, IL 61602", "us"))
raw_records.append(("S2-10003", "Payne Logistics Corp", "3315 Fremont St, Peoria, IL", "us"))
raw_records.append(("S3-10004", "Fremont Enterprise Solutions", "Peoria, IL", "us"))
raw_records.append(("S2-10005", "Wayne Enterprises Inc", "3315 Main St, Peoria, IL", "us"))

# Preset 2 & 3 Cluster (India: Hotel Enterprises)
raw_records.append(("S2-20001", "Hotel Enterprises Pvt Ltd", "WZ-187C Shop No.13, 14 Kh. No. 27/15, 27/16, Village Tihar, New Delhi, West Delhi, Delhi", "india"))
raw_records.append(("S3-20002", "होटल एंटरप्राइजेज", "WZ-187C Shop 13, 14 Kh. No. 27/15, 27/16, Village Tihar, New Delhi, West Delhi, Delhi", "india"))
raw_records.append(("S2-20003", "Hotel Grand Enterprises", "Village Tihar, New Delhi", "india"))
raw_records.append(("S3-20004", "Enterprises India Ltd", "West Delhi, Delhi", "india"))

# Preset 4 Cluster (France: Thermal & Fils SASU)
# Preserved target entities for Preset 4 France near-tie reproduction
raw_records.append(("S3-258414643", "(SASU) Thermal & Fils", "N° 20 R Parmentier, Dunkerque", "france"))
raw_records.append(("S2-377106401", "Sasu Thermal & Fils", "20 R. PARMENTIER, DUNKERQUE", "france"))
raw_records.append(("S2-30003", "Thermal SARL", "20 Rue Parmentier, Dunkerque", "france"))
raw_records.append(("S3-30004", "Fils & Cie SAS", "Dunkerque, Hauts-de-France", "france"))

# ==============================================================================
# 2. GENERATE 10,000 DIVERSE SYNTHETIC US RECORDS
# ==============================================================================
for i in range(len(raw_records), 10000):
    src = "S2" if i % 2 == 0 else "S3"
    eid = f"{src}-{100000 + i}"
    style = random.random()
    if style < 0.4:
        bname = f"{random.choice(US_FIRST)} {random.choice(US_INDUSTRY)}"
    elif style < 0.7:
        bname = f"{random.choice(US_STEMS)} {random.choice(US_INDUSTRY)}"
    else:
        bname = f"{random.choice(US_FIRST)} {random.choice(US_STEMS)} {random.choice(US_INDUSTRY)}"
    
    if random.random() < 0.8:
        bname += f" {random.choice(US_LEGAL)}"
        
    st_num = random.randint(10, 9999)
    st_name = f"{st_num} {random.choice(US_STREET_NAMES)} {random.choice(US_STREET_TYPES)}"
    city, state, zipc = random.choice(US_CITIES)
    baddr = f"{st_name}, {city}, {state} {zipc}"
    raw_records.append((eid, bname, baddr, "us"))

# ==============================================================================
# 3. GENERATE 10,000 DIVERSE SYNTHETIC INDIA RECORDS
# ==============================================================================
for i in range(10000, 20000):
    src = "S2" if i % 2 == 0 else "S3"
    eid = f"{src}-{200000 + i}"
    city, state, pin = random.choice(IN_CITIES)
    plot_num = random.randint(1, 999)
    loc = f"{random.choice(IN_LOCALITY_NAMES)} {random.choice(IN_LOCALITY_TYPES)}"
    baddr = f"Plot {plot_num}, {loc}, {city}, {state} {pin}"
    
    # 25% Native Devanagari script records
    if random.random() < 0.25:
        dev_base, _ = random.choice(DEVANAGARI_BASES)
        sfx = " प्राइवेट लिमिटेड" if random.random() < 0.5 else (" लिमिटेड" if random.random() < 0.7 else "")
        bname = f"{dev_base}{sfx}"
    else:
        style = random.random()
        if style < 0.4:
            bname = f"{random.choice(IN_FIRST)} {random.choice(IN_INDUSTRY)}"
        elif style < 0.7:
            bname = f"{random.choice(IN_STEMS)} {random.choice(IN_INDUSTRY)}"
        else:
            bname = f"{random.choice(IN_FIRST)} {random.choice(IN_STEMS)} {random.choice(IN_INDUSTRY)}"
        if random.random() < 0.85:
            bname += f" {random.choice(IN_LEGAL)}"
            
    raw_records.append((eid, bname, baddr, "india"))

# ==============================================================================
# 4. GENERATE 10,000 DIVERSE SYNTHETIC FRANCE RECORDS
# ==============================================================================
for i in range(20000, 30000):
    src = "S2" if i % 2 == 0 else "S3"
    eid = f"{src}-{300000 + i}"
    fn = random.choice(FR_FIRST)
    ind = random.choice(FR_INDUSTRY)
    leg = random.choice(FR_LEGAL)
    style = random.random()
    if style < 0.35:
        bname = f"{fn} {ind} {leg}"
    elif style < 0.6:
        bname = f"{leg} {fn} {ind}"
    elif style < 0.8:
        bname = f"{fn} & {random.choice(FR_FIRST)} {leg}"
    else:
        bname = f"{fn} {ind}"
        
    st_num = random.randint(1, 250)
    st_name = f"{st_num} {random.choice(FR_STREET_TYPES)} {random.choice(FR_STREET_NAMES)}"
    city, region, postal = random.choice(FR_CITIES)
    baddr = f"{st_name}, {city}, {region}"
    raw_records.append((eid, bname, baddr, "france"))

print(f"Generated {len(raw_records)} synthetic records across US, India, France.")

# ==============================================================================
# 5. RUN THROUGH REAL NORMALIZATION PIPELINE
# ==============================================================================
print("Running normalization pipeline on synthetic corpus...")
norm_rows = []
for eid, name, addr, country in raw_records:
    c = country.strip().lower()
    full, core, compact, alias = normalize.norm_name(name, tr["name"], c)
    atoks, state, nums = normalize.norm_addr(addr, c, tr["addr"])
    nl = normalize.lite(name, tr["name"])
    al_lite = normalize.lite(addr, tr["name"])
    sc = normalize.script_of_text(name)
    norm_rows.append((eid, c, full, core, compact, alias, atoks, state, nums,
                      nl, al_lite, sc, name, addr))

COLS = ["entity_id", "country", "name_full", "core", "compact", "alias", "addr", "state", "nums",
        "name_lite", "addr_lite", "script", "business_name", "business_address"]

df = pl.DataFrame(norm_rows, schema=COLS, orient="row")
output_parquet = DEMO_DIR / "synthetic_database.parquet"
df.write_parquet(output_parquet)
print(f"Saved {output_parquet.name} ({output_parquet.stat().st_size / (1024*1024):.2f} MB)")

# ==============================================================================
# 6. COMPUTE SYNTHETIC IDF DICTIONARY (EXACT BUILD_IDF() FORMULA)
# ==============================================================================
print("Computing synthetic IDF dictionary using exact features.build_idf() formula...")
cnt = Counter()
for col in ("core", "addr"):
    for toks in df[col].str.split(" ").to_list():
        cnt.update(set(toks))
n = len(df)
synthetic_idf = {t: math.log(n / c) for t, c in cnt.items() if t}

output_idf = DEMO_DIR / "synthetic_train_idf.json.gz"
with gzip.open(output_idf, "wt", encoding="utf-8") as f:
    json.dump(synthetic_idf, f)
print(f"Saved {output_idf.name} ({output_idf.stat().st_size / (1024*1024):.2f} MB, {len(synthetic_idf):,} tokens)")
